### PR TITLE
Add BlackBox (#125)

### LINKED ISSUE #125: Log Data to Latest.log
**Is your feature request related to a problem? Please describe.**
The problem is, data related to the state of a player account is inside Minecraft, and if one wants to automate things outside of minecraft, one must export data.   

**Describe the solution you'd like**
A module called "LogData" with checkboxes for various data -- current player coordinates, current player speed, etc.  I would like the ability to report telemetry to the latest.log file.

**Describe alternatives you've considered**
I have written programs to track the data coming out of Latest.log, however little of it relates to current in game player state so there are limited things that one can do.   

**Additional context**
I have written many programs in the past that send a text message to my phone under certain circumstances.   I generally use TCL to read data from files, and under certain conditions send messages.   

I wrote an extensive program to track my position in Q while in non-prio Q, make predictions, detect restarts, etc, and send notifications to my cell phone.   I could literally be away from the keyboard, and I would get data that would allow me to plan daily activities without running back to my computer to check what position I was in Q.   

Right now, one of my accounts is on a long walk and I am forced to use a slower travel method than I am used to but, it slips out of a groove and travels even slower from time to time, or can be stopped by grief.    It would be an option to write a minder program that alerts me when my player stops moving, or when its speed is reduced, so I can return to my computer and get it back on track.   

There are means to log death coordinates, however, a log of live coordinates leading to the death would sometimes be useful.   

The VisualRange detections are far more interesting to read in the logs in hindsight, if one can look up the coordinates where the player was when these alerts were made.

### PR DESCRIPTION
**Pull request by ZimnyCat**
Closes #125

### CODE REVIEW

**Comment by ToxicAven** [comment]
Calling on @HoratioGamer, does this satisfy your request?

Edit: This should probably be implemented as a plugin

**Comment by ZimnyCat** [comment]
> This should probably be implemented as a plugin

good idea

**Comment by HoratioGamer** [comment]
I read the code but have not seen it in Lambda yet.   It looks good but I am wondering why roundToInt() on speed but not on coords.   Decimal places on coords are less interesting than on speed.

Thank you for creating this module.

**Comment by ZimnyCat** [comment]
> but I am wondering why roundToInt() on speed but not on coords

mc.player.position is a BlockPos, its coordinates dont have decimal places

**Comment by huddy987** [comment]
Thank you for your contribution. I think the main thing we need to figure out is whether to include this as a core module or a plugin. @Avanatiker let me know what you think

**Comment by ToxicAven** [comment]
This should be a plugin.

**Comment by ZimnyCat** [comment]
> This should be a plugin.

oki, give me some time

**Comment by ToxicAven** [comment]
No rush!

**Comment by ZimnyCat** [comment]
https://github.com/ZimnyCat/BlackBox

**Pull request closed without merging**
