### PR TITLE
Clean up bash file

### PR DESCRIPTION
**Pull request by mmvanheusden**
cleaned up bash file referencing to the styleguide by google(https://google.github.io/styleguide/shellguide.html)

also changed /bin/sh shebang thingy to /bin/bash because thats what everyone does apparently (https://askubuntu.com/a/141932)

also sorry for the stupid commit titles lol, im still learning all this git stuff

### CODE REVIEW

**Comment by Avanatiker** [comment]
Revert the comment changes they are redundant. Ill add the shebang though

**Comment by Avanatiker** [comment]
Also for good practice start giving your commits a proper name/description

**Comment by ToxicAven** [comment]
In most distros, /bin/sh should be a symlink to /bin/bash anyways. This pull should not be merged, as no content is being added, or modified in any substantial way.

EDIT: `does something with gradle` isn't a very professional, or helpful comment to add.

**Comment by mmvanheusden** [comment]
yeah you are right, but as explained in that askubuntu link i provided,
*some* distros do not have that symlink so there is nothing wrong with changing that is it?

**Comment by ToxicAven** [comment]
Also quoted from the comments of the AskUbuntu link:

> Your first paragraph is quite misleading. "sh" is not a shell at all, but a symlink to the currently configured *system shell*, which on Linux systems is usually either bash or dash (recent versions of Ubuntu using the latter). – 
thomasrutter

**Comment by Avanatiker** [comment]
Not really

**Comment by mmvanheusden** [comment]
?

**Comment by ToxicAven** [comment]
This was closed due to being a useless PR.

**Pull request closed without merging**
