### PR TITLE
fix: Incorrect change

### PR DESCRIPTION
**Pull request by 5HT2**
You will need to allow permission in the codefactor dashboard [here](https://www.codefactor.io/dashboard) or remove the badge entirely.

### CODE REVIEW

**Comment by Natan515** [comment]
I can't accept it yet sorry, they told me to wait till they update the settings.

**Comment by 5HT2** [comment]
It takes like 30 seconds to approve it in the dashboard, or remove the badge if you don't want to fix it.

**Comment by Avanatiker** [comment]
Yea we work on the permission stuff :) thanks a lot! this was just a bridging solution

**Comment by Natan515** [comment]
> It takes like 30 seconds to approve it in the dashboard, or remove the badge if you don't want to fix it.

Yes but they asked me to wait till they fix perms. Even if it takes 1 sec

**Pull request merged**
