### PR TITLE
Add 85km/h YPort mode to Speed

### PR DESCRIPTION
**Pull request by Doogie13**
**Describe the pull**
~~Add a simple Boost (aka Ground Strafe, aka Alerithe) mode to Speed, similar to YPort in function but completely silent~~
85km/h NCP YPort

**Describe how this pull is helpful**
Allows the player to move faster on ground, bypasses better than the current OnGround

**Additional context**
[Video](https://youtu.be/6jyTk-blHGY) on a local NCP server, [Updated video](https://youtu.be/3Fep_5ZusqQ)

### CODE REVIEW

**Comment by mmvanheusden** [comment]
based

**Comment by Doogie13** [comment]
Please note this speed mode will not work on Updated-NCP as it relies on changing Y speed rapidly which flags but this will work on normal NCP (non strict servers)

**Comment by Avanatiker** [comment]
Any big servers where this works?

**Comment by Doogie13** [comment]
> Any big servers where this works?

It will work in any situation a good OnGround bypasses (lambda OnGround is not a proper OnGround since it doesn't try to adjust Y at all). For example: 2b2t when under blocks, 2b2tpvp, most servers with normal NCP movement checks (a LOT of clones).

**Comment by Doogie13** [comment]
I will try this on some popular servers when I am home and send a video

**Comment by Doogie13** [comment]
Ok so i cba to make a video but i tested it on these servers:
2b2tpvp -> O
CPvP.cc -> X (Works under blocks)
2b2t.dev -> X (Works under blocks)
5b5t.org -> O
9b9t.org -> O
tree.ac (random NCP test server) -> O

basically it worked in all places using NCP speed checks (cpvp.cc uses very strict custom speed checks, 2b2t.dev uses U-NCP)
and where it works, it works flawlessly, other than a couple hiccups when moving between under and not under blocks on any server (literally 1 rubberband and then it works fine again)

**Comment by Avanatiker** [comment]
Needs merged ongrounds

**Comment by Doogie13** [comment]
This is incoming. There will be an option to accelerate and an option not to since not accelerating is more consistent for some things but accelerate is faster for travel and flat duels

**Comment by Doogie13** [comment]
Made it a proper onground/yport now, ~~I will test on different servers shortly~~
Edit, no need to test on other servers since this works the same as literally every other YPort and I cba

**Comment by Doogie13** [comment]
[Video](https://youtu.be/3Fep_5ZusqQ) on local NCP server. This will work anywhere normal OnGround/YPort will.

**Comment by Doogie13** [comment]
Unless there is any glaring flaws in this code, I have pulled a Techale and added as many options as one would need for any server ever. You can just use defaults most of the time.

**Comment by Doogie13** [comment]
DO NOT MERGE YET

**Comment by Doogie13** [comment]
Once this next push is tested, this will be finally ready to merge

**Comment by Doogie13** [comment]
Has anyone tested this? I tested it on NCP but not Updated-NCP, nor 2bs fork.

**Comment by Avanatiker** [comment]
I tested it on 2b and i cant find a setting that works :c maybe i did it wrong?

**Comment by Doogie13** [comment]
I tested it on 2b2t and got results similar to strafe, which is good becuase this looks smoother. also this is more meant for normal ncp so having it work on 2b2t with some work is very nice

**Comment by Doogie13** [comment]
image
2b2t.org config 28-29km/h and fairly consistent, though this is more for NCP rather than UpdatedNCP

**Comment by czho** [comment]
based

**Comment by Doogie13** [comment]
can this not be merged? idk how I can improve it

**Comment by mmvanheusden** [comment]
Is this still going to be merged? I think it is unacceptable that this has been open for 6 months without being looked at

**Comment by NCPUser** [comment]
YPort No Speed Mod
What Speed?

**Comment by Doogie13** [comment]
> YPort No Speed Mod
> What Speed?

Excuse me?

**Comment by Avanatiker** [comment]
Finally found a working mode for 2b: Mode: Strafe, Auto Jump: true, AirSpeedBoost: 0.037 and Only strafe on overhead: true gives 42 km/h

**Review by Avanatiker — APPROVED** [review]

**Comment by Avanatiker** [comment]
Sorry for this being stuck here for so long!

**Pull request merged**
