### PR TITLE
Changes to the script

### PR DESCRIPTION
**Pull request by mmvanheusden**
the script now also generates the IntelliJ runs because why not

### CODE REVIEW

**Comment by Avanatiker** [comment]
My bad

**Comment by mmvanheusden** [comment]
@Avanatiker What's the status on this? i just build the project with this script on my freshly installed crappy laptop and i can confirm it works fine.

**Comment by Avanatiker** [comment]
The build script may be unsafe according to my IDEA: In POSIX sh, SECONDS is undefined. See SC2039. Line 29. What does it mean?

**Comment by mmvanheusden** [comment]
> The build script may be unsafe according to my IDEA: In POSIX sh, SECONDS is undefined. See SC2039. Line 29. What does it mean?

Yeah POSIX is some ancient linux bash standard or something but on most distros this should work just fine and if it doesn't, the elapsed time will just show 0 minutes and 0 seconds

**Review by Avanatiker — APPROVED** [review]

**Pull request merged**
