### PR TITLE
Added Criticals -> Edit mode

### PR DESCRIPTION
**Pull request by Doogie13**
**Describe the pull**
This pull adds Criticals -> Edit mode for 2b2t.org and other UpdatedNCP servers.

**Describe how this pull is helpful**
The current Criticals modes are lacking for 2b2t and other UpdatedNCP servers .

**Additional context**
This has been tested on eu.loyisa.cn and the bypass has been tested on 2b2tpvp.net, so should work on all versions of NCP.

### CODE REVIEW

**Comment by NCPUser** [comment]
hypixel bypass?

**Comment by Doogie13** [comment]
I haven't tested it there, might work. Just use Lambda on anarchy servers.

**Comment by Gentleman2292** [comment]
On my way to skid

**Comment by Doogie13** [comment]
UPDATE: This does flag `falldist_mismatch` but idk if 2b2t has that check enabled (eu.loyisa.cn has it disabled, 2b2t.dev has it enabled). Can someone with queue test these crits on 2b2t.org? A positive result would be that you can attack entities, negative would cancel the hit alltogether.

**Review by Avanatiker — APPROVED** [review]

**Comment by Avanatiker** [comment]
Thanks a lot for your PR :)

**Pull request merged**
