### PR TITLE
Disable some modules in singleplayer

### PR DESCRIPTION
**Pull request by mmvanheusden**
Some modules glitch out in singleplayer, so I prevented them from being enabled.

### CODE REVIEW

**Comment by Avanatiker** [comment]
Should be a manager that listens to ToggleModuleEvent and then looks in list of as broken flagged modules.

**Comment by mmvanheusden** [comment]
I don't really know how to code that and I think that is really inefficient because you also need to have a list with a personalized message for each module

**Comment by Avanatiker** [comment]
Actually even better could be a Module tag to make it automatically not activate on singleplayer....

**Comment by Avanatiker** [comment]
Actually its quite a problem for most modules and i think its common sense to just not use the mod in single player. Will close this thanks though!

**Pull request closed without merging**
