### PR TITLE
Add coal ore and lava to default XRay list

### PR DESCRIPTION
**Pull request by ZimnyCat**
Adds coal ore and liquids to help poor players.

### CODE REVIEW

**Comment by huddy987** [comment]
I'm just curious, why water?

**Comment by Avanatiker** [comment]
Hey! Thanks a lot for contributing :3 Lava makes kinda sense but why the water? it will block the view too much. also i dont think coal is nessesessary because you can find it within seconds without xray

**Comment by ZimnyCat** [comment]
I usually need a minute to find coal.

**Comment by scorbett123** [comment]
You can just add it manually then when you need to find coal.

**Comment by ZimnyCat** [comment]
> You can just add it manually then when you need to find coal.

then what's the point of default list?

**Comment by scorbett123** [comment]
> > You can just add it manually then when you need to find coal.
> 
> then what's the point of default list?

Common things that are usually hard to find, such as diamonds, coal is so common that it would almost completely block your view.

**Comment by Natan515** [comment]
I believe that cus u can just add blocks three by commend; we don't need to add coal or lava

**Comment by Avanatiker** [comment]
We figuered that adding this to the default list does not really help. those edge cases can be tackeled using the command to easiely add new blocks. For the average user this will not enhance the user experience. We still thank u for sharing your idea and you are welcome to make different sugguestions :)

**Pull request closed without merging**
