### PR TITLE
Add a debug info hud element

### PR DESCRIPTION
**Pull request by mmvanheusden**
It displays all kinds of debug info
Screenshot from 2022-02-28 10-54-58

Might be useful for finding bypasses I guess

### CODE REVIEW

**Comment by ToxicAven** [comment]
So far, this looks better suited as a plugin.

**Comment by mmvanheusden** [comment]
> 

Yeah, true, lets wait for Constructor's opinion

**Comment by huddy987** [comment]
Overall nice idea, I think it makes sense to make it a plugin though because most average people won't use it

**Comment by Avanatiker** [comment]
I think that every of those entries should be a separate HUD element so people can customize. We could think about adding some of the ideas to the current HUD pool.

I think those could be used:
- BedLocation
- Velocity
- Difficulty
- Gamemode

What do you guys think about it?

**Comment by Avanatiker** [comment]
I think that every of those entries should be a separate HUD element so people can customize. We could think about adding some of the ideas to the current HUD pool.

I think those could be used:
- BedLocation
- Velocity
- Difficulty
- Gamemode

What do you guys think about it?

**Comment by mmvanheusden** [comment]
Sure, i will start working on it

**Comment by ToxicAven** [comment]
I still think that this should be a plugin, since the average person would still not use these.

**Comment by Avanatiker** [comment]
I mean stuff like OnGround should definitly be only in a plugin but i think that bed thing for example could be actually useful as long as it works throughout sessions and with different servers not sure.

**Comment by Avanatiker** [comment]
Closed bc inactive

**Pull request closed without merging**
