### PR TITLE
Add checksum generation to the workflow

### PR DESCRIPTION
**Pull request by ToxicAven**
There were no checksum generation actions, so I had to write an action for that. I can say firsthand, github actions are a pain.

[Source of action](https://github.com/ToxicAven/generate-checksum-file)

### CODE REVIEW

**Comment by chinmaygovind** [comment]
breathe

**Comment by ToxicAven** [comment]
> breathe

I did, took me a minute

**Comment by czho** [comment]
We might want to make the actions repo be in the github organization.

**Comment by ToxicAven** [comment]
> We might want to make the actions repo be in the github organization.

No, as this is a personal actions run I made outside of the lambda project. I made it to be used by the lambda project, not to be owned by the lambda project.

**Review by Avanatiker — APPROVED** [review]

**Comment by Avanatiker** [comment]
Thanks a lot :) cool tool

**Comment by chinmaygovind** [comment]
your hard work paid off

**Pull request merged**
