### PR TITLE
Plugin updater and custom class loader

### PR DESCRIPTION
**Pull request by scorbett123**
This adds to option to update previously installed plugins.

It also implements a custom class loader that doesn't require closing. This has been tested on windows, it would be preferable for people to test this on other OS's.

### CODE REVIEW

**Comment by Avanatiker** [comment]
Thanks a lot! will check it out later

**Comment by Avanatiker** [comment]
Sry for not merging yet. I tried to make it more stable while realizing that our current plugin menu should get a big overhaul and get moved to the ClickGUI so people find the plugin stuff. That will take some time.

**Comment by scorbett123** [comment]
> Sry for not merging yet. I tried to make it more stable while realizing that our current plugin menu should get a big overhaul and get moved to the ClickGUI so people find the plugin stuff. That will take some time.

What issues have you been having with it? I have been testing it so far with no issues (except the running out of github api requests).

**Comment by Avanatiker** [comment]
The problem is right now i need to fix these first:
- updating to Kotlin 1.5.30 causes some weird bugs for the PluginConfig class
- problem with loading hud settings
- move plugin list from separate GUI to ClickGUI
- solve the API request limit problem

Also concerning the bugs in this pr:
- it can cause crashes when deleting the list entry
- State render does not update properly

**Comment by ToxicAven** [comment]
bump

**Comment by Doogie13** [comment]
based. you can reload by just uninstalling and reinstalling the plugin in plugman

**Comment by Avanatiker** [comment]
Ok i finally did the plugin gui refactor and implemented your costum class loader into it. Sadly this pr is not working on the new code base bc it also contains code for plugin updating using the old manager. I have to close this but thanks for contributing the code for the loader and updater!

**Pull request closed without merging**
