### PR TITLE
Refactor build script. Remove bloat.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ToxicAven** [comment]
This needs to be checked cross client. Last time we upgraded reflections, Future Client compatibility broke.

**Comment by ghost** [comment]
> This needs to be checked cross client. Last time we upgraded reflections, Future Client compatibility broke.

I haven't updated reflections?

**Comment by ToxicAven** [comment]
I'm just making an example.

**Comment by ghost** [comment]
> I'm just making an example.

(Ofc with Future as well). Launched fine without any crashes/issues that I could find.
Screenshot (1517)

**Review by Avanatiker — APPROVED** [review]

**Comment by TudbuT** [comment]
Why is jUnixSocket excluded? That seems like it would break discordrpc's linux compatibility.

**Comment by ToxicAven** [comment]
Yes, this pull broke it, but why are you necroposting a merged pull? It is fixed now.

**Pull request merged**
