### PR TITLE
Rewrite Scaffold module

### PR DESCRIPTION
**Pull request by Doogie13**
**Describe the pull**
This pull replaces the old kami blue scaffold with an actually usable one

**Describe how this pull is helpful**
This will allow people to use scaffold without crying

**Additional context**
UwU

### CODE REVIEW

**Comment by Doogie13** [comment]
A crash has been found, lemme fix

**Comment by Doogie13** [comment]
This now is ready to push to the main client. This scaffold has all the bells and whistles any anarchy scaffold could need

**Comment by Avanatiker** [comment]
First of all thanks a lot for your first contribution to the main project! I really appreciate it :smile:
Unfortunately i get a lot of desyncs even on unprotected servers. Thus it does not work on 2b which is kinda important for the mod.

This is a nice prototype though and i like the way it allows you freely to move. Keep it up!

**Comment by Doogie13** [comment]
I shall look into this, perhaps locking rotation while scaffold is on and we are moving at all rather than moving rotation only when placing.

**Comment by Doogie13** [comment]
Oh, and do note that using any kind of extend on 2b2t can lead to blocks failing to place, since you would be looking at an obscured surface

**Comment by ItCameFr0mMars** [comment]
are all of the desyncs fixed? I really want this to be in the main client

**Review by aegires — APPROVED** [review]

**Comment by mmvanheusden** [comment]
The scaffold work great in singleplayer, but is still terrible with NCP, even on the default config.

**Comment by ChillerDragon** [comment]
Tested on 2b2t. On current master the scaffold is barley working. One can easily fall.

This pr makes it fairly secure even on 2b2t. But it is still a bit sluggish and tends to get stuck. Also there is no block placing sound anymore.

**Comment by mmvanheusden** [comment]
this

**Comment by Doogie13** [comment]
> Also there is no block playing sound anymore.

I might make this a setting

**Comment by Avanatiker** [comment]
ill add a building engine to lambda to make all modules build more efficient. unfortunately this PR does not fit into this system. thanks for your effort tho! please keep it up. ill close this for now. better scaffold will need to wait for next version.

**Pull request closed without merging**
