### PR TITLE
remove modules + merge into NoRender

### PR DESCRIPTION
**Pull request by ItCameFr0mMars**
**Describe the pull**
Remove un-needed modules

**Describe how this pull is helpful**
fulfill tasks for release

**Additional context**
none

### CODE REVIEW

**Comment by IUDevman** [comment]
Bro colored signs is my favorite module

**Comment by ItCameFr0mMars** [comment]
I added HideArmor to NoRender

**Comment by ItCameFr0mMars** [comment]
> Bro colored signs is my favorite module

sorry

**Comment by czho** [comment]
Combine anti overlay aswell

**Comment by ItCameFr0mMars** [comment]
I will keep working on merging the other modules when I have time.

**Comment by ItCameFr0mMars** [comment]
everything has been merged

**Review by czho — CHANGES_REQUESTED** [review]
You gotta make sure each thing has a setting, u can't just test for if the module is enabled.

**Comment by ItCameFr0mMars** [comment]
Pretty sure I have settings for all, I’ll check once I am able to. If you lmk what settings are missing it would be great! @czho

**Review by ItCameFr0mMars — COMMENTED** [review]
ignore this messgae

**Review by Avanatiker — APPROVED** [review]

**Pull request merged**
