### PR TITLE
Add ClientSideTime module

### PR DESCRIPTION
**Pull request by Baitinq**
This patch adds the ClientSideTime module, which allows the user to change their client-side world time. It currently has two modes; TICKS and REAL_WORLD_TIME. The former allows you to specify the world time as ticks, and the latter uses your current computer time as the world time.

:)

### CODE REVIEW

**Comment by Avanatiker** [comment]
Thats a fun idea but i wonder if there is any specific use to it you personally need it for?

**Comment by Baitinq** [comment]
No specific use case, just remembered it from other clients and I find it really neat (maybe it could have a use where you dont want fullbright but you want more light?). Maybe I could make it into a plugin if you prefer :)

P.S. Or it could be like the ChatTimestamp module, just a little cool builtin module

**Comment by Avanatiker** [comment]
This could fit into Fullbright as other mode then gamma etc.

**Comment by Avanatiker** [comment]
this could fit to AntiWeather maybe? not sure yet.

**Comment by Baitinq** [comment]
> this could fit to AntiWeather maybe? not sure yet.

i dont see how it could really integrate with antiweather, maybe if we create a parent module that holds them both?. but i do believe this would be cool to have as its own module :)

**Review by Avanatiker — APPROVED** [review]

**Pull request merged**
