### PR TITLE
Make AutoExcuse external only

### PR DESCRIPTION
**Pull request by SnowshoeIceboot**
external mode didn't even work before, now it does, and is the default. also removed the built-in messages because they are pointless.

### CODE REVIEW

**Comment by Avanatiker** [comment]
Anyone who doesnt want to remove the default messages? Also why are u not using the Spammer module for this? you also call the vars spammer. This module is for sending excuses on death

**Comment by SnowshoeIceboot** [comment]
changed var name.

**Comment by mmvanheusden** [comment]
I like the goofyness of the default messages

**Comment by SnowshoeIceboot** [comment]
you can put any message you want in excuses.txt, just like spammer

**Comment by mmvanheusden** [comment]
> you can put any message you want in excuses.txt, just like spammer

You could always do that

**Comment by SnowshoeIceboot** [comment]
> You could always do that

nope, it would just load the default messages every time even if you made excuses.txt

**Comment by SnowshoeIceboot** [comment]
Added in-order option

**Comment by Avanatiker** [comment]
iam still confused why you dont use spammer for this

**Comment by SnowshoeIceboot** [comment]
> iam still confused why you dont use spammer for this

spammer runs on a timer, autoexcuse runs on death

**Review by Avanatiker — APPROVED** [review]

**Review by Avanatiker — APPROVED** [review]

**Pull request merged**
