### PR TITLE
Refactor Flight

### PR DESCRIPTION
**Pull request by Doogie13**
**Describe the pull**
Completely rewrote the old KAMI Blue Packet flight and Static flight

**Describe how this pull is helpful**
The new Packet flight mode is much faster and feature rich than the previous version. It allows for faster movement, adjustable factor, seperate factor for when concealing and when bypassing (including factors below 1), better antikick measures, better control inside blocks.

The new Static flight will not close your elytra, meaning it can be used for the 2b2t elytrafly bypass instead of requiring future.

**Additional context**
[Video on 2b2tpvp.net](https://youtu.be/P0rWp8BYTT0)

### CODE REVIEW

**Comment by CozyMeli-gitv2** [comment]
this looks fuckin seek via the vid you linked. nice job

**Comment by czho** [comment]
very nice, i hope to see this merged :)

**Comment by nickcat1** [comment]
Looks good.

**Comment by nickcat1** [comment]
I messed around with this on 2b2t. It killed me instantly.

**Comment by Doogie13** [comment]
> I messed around with this on 2b2t. It killed me instantly.

Killed or kicked? This is designed for less strict servers like 2b2tpvp but I have used a very similar packetfly I made on 2b2t with no issue, can you record a video?

**Comment by nickcat1** [comment]
I was killed and kicked. I'm at my base right now so I can't make a video. I jumped off a small ledge and enabled flight with full armor and a totem.

**Comment by Doogie13** [comment]
> I was killed and kicked. I'm at my base right now so I can't make a video. I jumped off a small ledge and enabled flight with full armor and a totem.

Does this happen with other packet fly modules?

**Review by Avanatiker — APPROVED** [review]

**Pull request merged**
