### PR TITLE
Refactor Jesus

### PR DESCRIPTION
**Pull request by Doogie13**
**Describe the pull**
Rewritote Jesus mode for NCP and UpdatedNCP

**Describe how this pull is helpful**
This will allow users to use Jesus on 2b2t.org and many more servers.

**Additional context**
This is a port of my Jesus from TwelveMod.

### CODE REVIEW

**Comment by Blade-ua** [comment]
i have own jesus for last ncp.
15-20 bps but only for 1-2 seconds(

**Comment by Doogie13** [comment]
> i have own jesus for last ncp.
> 15-20 bps but only for 1-2 seconds(

This is like 25km/h on strict mode and 20km/h on normal mode.

**Comment by nickcat1** [comment]
Looks good.

**Comment by NCPUser** [comment]
good

**Review by Avanatiker — APPROVED** [review]

**Review by Avanatiker — APPROVED** [review]

**Comment by Avanatiker** [comment]
sorry for taking so long. I had to first familiarize myself with the problem which took some motivation. Thanks for the pull request! feel free to work on some of the issues or features i sent you :)

**Pull request merged**
