### PR TITLE
Adding MapDownloader

### PR DESCRIPTION
**Pull request by P529**
This is a module that saves maps that are displayed in item frames to a png file.

### CODE REVIEW

**Comment by 5HT2** [comment]
Shouldn't this be a plugin? This should probably also re-use the utilities that MapPreview uses.

**Comment by czho** [comment]
This should be a plugin.

**Comment by P529** [comment]
> Shouldn't this be a plugin? This should probably also re-use the utilities that MapPreview uses.

I was talking to Constructor about it being a plugin or an addition to Lambda itself and we decided it is probably better as a module in the main client. And the thing about MapPreview is that it doesnt share any code and MapPreview is only showing maps in your inventory. 

MapDownloader saves every map in your render distance to file so quite different. Or are you saying it should be an option in MapPreview to save the Map you preview to file? That sounds like a different module.

**Comment by Avanatiker** [comment]
We need to solve the plugin github api requests limit to add more plugins to the list without having people beeing api limited. thats why i thought it could be in the client for now until we found a solution

**Comment by 5HT2** [comment]
> We need to solve the plugin github api requests limit 

I'll happily discuss working around this with you on Discord, ping me.

**Comment by Avanatiker** [comment]
What if we combine it with MapPreview as one module the code isnt that long and kinda fits.

**Review by Avanatiker — APPROVED** [review]

**Pull request merged**
