### PR TITLE
I have Just updated baritone version, Fix #43

### LINKED ISSUE #43: update baritone
update baritone to the latest version (1.2.15)

### PR DESCRIPTION
**Pull request by Natan515**
Ye there is not a lot to say about that, there is a new version so now we can enjoy it.

### CODE REVIEW

**Comment by Natan515** [comment]
I mean, I hope its that simple, if not let me know pls. I have no idea why it doesn't manage to build

**Comment by scorbett123** [comment]
There have been some api changes that will need to be updated.

**Comment by Natan515** [comment]
I'll look into it, thank you!

**Comment by Natan515** [comment]
From what I'm looking right now, the new update was made but wasn't added to the website yet https://baritone.leijurv.com

**Pull request closed without merging**
